name = "doula-website"
compatibility_date = "2024-12-01"
pages_build_output_dir = "dist"

[vars]
ADMIN_EMAIL = "Maryna@heldandheardcare.com"
JWT_SECRET = "hh2026-m7k2x9-secretkey-p4q8r1"
RESEND_API_KEY = "re_jWTyRe3H_7iQ92YS5AWiJMRapYY8youmD"

[[d1_databases]]
binding = "DB"
database_name = "held-heard-db"
database_id = "dd8cf41f-beb3-4215-a9f7-4d2f2f3251f7"
